services:
  nodejs-appcriteo:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: nodejs-appcriteo
    security_opt:
      - no-new-privileges:true
    networks:
      - appcriteo
    volumes:
      - ../logs:/var/www/app/logs
    restart: always
  nginx-appcriteo:
    image: nginx:1.22.0
    container_name: nginx-appcriteo
    security_opt:
      - no-new-privileges:true
    ports:
      - ${DOCKER_PORT}:443
    depends_on:
      - nodejs-appcriteo
    networks:
      - appcriteo
    env_file:
      - .env
    volumes:
      - ../docker/nginx/ssl:/etc/nginx/ssl
      - ../docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ../docker/nginx/conf.d/ssl-${ENVIRONMENT}:/etc/nginx/conf.d/ssl-active.conf
      - ../docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../logs:/var/log/nginx
    restart: always
networks:
  appcriteo:
    driver: bridge
